// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode
// we create 1 variable that the user input his email 
// and then  check if his email valid or no  for this  
// we need 2 variables  for check if there is  @ and dot
// in case there are no, print one message that "you miss" @ or dot 
// or missing together return invalid 
// and the if the email contain all of these(@ , dot) print the message your email valid
//
//
// paste your JS generated by blockly below here
var email, at, dot;


email = window.prompt('your email');
at = email.indexOf('@') + 1;
dot = email.indexOf('.') + 1;
if (dot == 0 && at == 0) {
  window.alert('your email invalid');
} else {
  if (at == 0) {
    window.alert('you miss (@) your email invalid');
  } else if (dot == 0 || dot < at) {
    window.alert('you miss  (.) your email invalid');
  } else if (dot > at || dot < at) {
    window.alert('your email valid');
  }
}

