// Rewrite the instructions in your own words
//  


// Write the objectives and the tests

// Write the pseudocode
// create variable for acronyms to prompt for text 
//create variable for acronyms
//create a variable for result
//for each item in the list to result open the text in the item 
//with the first letter
//print result
//   


// paste your JS generated by blockly below here
var result, acr, phrase, item;


result = '';
acr = window.prompt('Enter Your Word');
phrase = acr.split(' ');
for (var item_index in phrase) {
  item = phrase[item_index];
  result += String(item.charAt(0).toUpperCase());
}
window.alert(result);