// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode
// 1.we need 2 variable  for computer and user
// 2.when the user input any value's rock or paper or scissors  
// 3. the  pc give  value  random  and compare between the value's users and value's random
//5. and then print the message that clear the result of game (win or lose)    
// paste your JS generated by blockly below here
var machina, user;

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}


machina = Number(window.prompt('abc'));
user = mathRandomInt(1, 3);
if (user == machina) {
  window.alert('tie');
}
if (machina == 1) {
  if (user == 2) {
    window.alert('You lose 1-3. Try again!');
  } else if (user == 3) {
    window.alert('Good job! You win 3-2');
  }
}
if (machina == 2) {
  if (user == 3) {
    window.alert('You lose 1-3. Try again!');
  } else if (user == 1) {
    window.alert('Good job! You win 3-2');
  }
}
if (machina == 3) {
  if (user == 1) {
    window.alert('You lose 1-3. Try again!');
  } else if (user == 2) {
    window.alert('Good job! You win 3-2');
  }
}